name: slack-approval
description: Custom action to send approval request to Slack from GitHub Actions
author: varu3

inputs:
  bot-token:
    description: "Slack bot token"
    required: true
  signing-secret:
    description: "Slack signing secret"
    required: true
  app-token:
    description: "Slack app token"
    required: true
  channel-id:
    description: "Slack channel ID"
    required: true
  mention-to-user:
    description: "Slack user ID to mention"
    required: false
  mention-to-group:
    description: "Slack group ID to mention"
    required: false
  authorized-users:
    description: "Slack user IDs who are authorized to approve or reject"
    required: false
  title:
    description: "Approval message title"
    required: false

branding:
  icon: plus
  color: green

runs:
  using: node20
  main: dist/index.js
